const properties=[
 {title:'4 Bedroom Detached Duplex',location:'Lekki Phase 1, Lagos',price:'₦185,000,000',numeric:185,type:'Duplex',status:'FOR SALE',beds:'4 beds',baths:'5 baths',size:'420 sqm',image:'https://images.nigeriapropertycentre.com/properties/images/3216700/06921da41444bc-luxury-5-bedroom-smart-home-with-swimming-pool-and-bq-detached-duplexes-for-sale-lekki-lagos.jpeg',slug:'lekki-4bed-duplex'},
 {title:'3 Bedroom Serviced Apartment',location:'Old Ikoyi, Lagos',price:'₦12,000,000',numeric:12,type:'Apartment',status:'FOR RENT',period:'/ yr',beds:'3 beds',baths:'3 baths',size:'210 sqm',image:'https://images.nigeriapropertycentre.com/properties/images/3326315/06983223c2e0e6-neatly-built-3bedroom-apartment-with-bqpoolgym-in-ikoyi-for-rent-ikoyi-lagos.jpeg',slug:'ikoyi-3bed-apartment'},
 {title:'4 Bedroom Terrace with BQ',location:'Ajah, Lagos',price:'₦96,500,000',numeric:96.5,type:'Terrace',status:'FOR SALE',beds:'4 beds',baths:'4 baths',size:'260 sqm',image:'https://www.superiteafrica.com/uploads/property_image/IMG-20250702-WA0213.jpg',slug:'ajah-terrace'},
 {title:'5 Bedroom Family Home',location:'GRA Ikeja, Lagos',price:'₦210,000,000',numeric:210,type:'Detached House',status:'FOR SALE',beds:'5 beds',baths:'6 baths',size:'650 sqm',image:'https://images.nigeriapropertycentre.com/properties/images/2985476/0687ac026dee98-on-1200sqm-land-6-bedroom-mansion-plus-study2-units-of-1-bedroom-bq-detached-duplexes-for-sale-gra-ikeja-lagos.jpg',slug:'ikeja-family-home'},
 {title:'2 Bedroom Starter Flat',location:'Sangotedo, Lagos',price:'₦4,200,000',numeric:4.2,type:'Flat',status:'FOR RENT',period:'/ yr',beds:'2 beds',baths:'2 baths',size:'95 sqm',image:'https://www.nairaland.com/attachments/13879261_2159148043448158738936644075895798052442500n_jpgdb4c45fa7d57bc332b489f2d643a13f6',slug:'sangotedo-2bed'},
 {title:'600 sqm Serviced Land',location:'Epe Corridor, Lagos',price:'₦18,000,000',numeric:18,type:'Land',status:'INVESTMENT',beds:'600 sqm',baths:'Serviced',size:'Title verified',image:'https://images.nigeriapropertycentre.com/properties/images/3384605/069b1ef65408a4-own-a-verified-property-in-epe-own-for-building-now-or-landbanking-residential-land-for-sale-epe-lagos.jpg',slug:'epe-serviced-land'}
];
const videos=[
 {title:'Inside a ₦185m Lekki duplex',subtitle:'Full walkthrough · 8 min',image:'https://images.nigeriapropertycentre.com/properties/images/3216700/06921da41444bc-luxury-5-bedroom-smart-home-with-swimming-pool-and-bq-detached-duplexes-for-sale-lekki-lagos.jpeg'},
 {title:'Is Epe land still worth it?',subtitle:'Market breakdown · 6 min',image:'https://images.nigeriapropertycentre.com/properties/images/3384605/069b1ef65408a4-own-a-verified-property-in-epe-own-for-building-now-or-landbanking-residential-land-for-sale-epe-lagos.jpg'},
 {title:'Renting in Ikoyi: what ₦12m gets you',subtitle:'Tour + costs · 5 min',image:'https://images.nigeriapropertycentre.com/properties/images/3326315/06983223c2e0e6-neatly-built-3bedroom-apartment-with-bqpoolgym-in-ikoyi-for-rent-ikoyi-lagos.jpeg'}
];
const grid=document.getElementById('propertyGrid');
function card(p){return `<div class="col-md-6 col-lg-4"><article class="property-card" role="button" tabindex="0" data-slug="${p.slug}" aria-label="View ${p.title}"><div class="property-image"><img src="${p.image}" alt="${p.title} in ${p.location}" loading="lazy"><span class="status-badge">${p.status}</span><button class="favorite" type="button" aria-label="Save ${p.title}" onclick="event.stopPropagation();this.classList.toggle('saved');this.textContent=this.classList.contains('saved')?'♥':'♡'">♡</button></div><div class="property-info"><h3>${p.title}</h3><p class="property-location">⌖ &nbsp;${p.location}</p><p class="property-price">${p.price} <small>${p.period||''}</small></p><div class="property-meta"><span>▱ ${p.beds}</span><span>♧ ${p.baths}</span><span>⌗ ${p.size}</span></div></div></article></div>`}
function render(list){grid.innerHTML=list.map(card).join('');document.getElementById('listingCount').textContent=`${list.length} ${list.length===1?'listing':'listings'}`;document.getElementById('noResults').classList.toggle('d-none',list.length>0);}
render(properties);
document.getElementById('videoGrid').innerHTML=videos.map(v=>`<div class="col-md-6 col-lg-4"><article class="video-card"><div class="video-thumb"><img src="${v.image}" alt="${v.title}" loading="lazy"><span class="video-play" aria-hidden="true">▶</span></div><div class="video-info"><h3>${v.title}</h3><p>${v.subtitle}</p></div></article></div>`).join('');
document.getElementById('propertySearch').addEventListener('submit',e=>{e.preventDefault();const location=document.getElementById('locationInput').value.trim().toLowerCase(),price=document.getElementById('priceInput').value,type=document.getElementById('typeInput').value;const filtered=properties.filter(p=>(!location||p.location.toLowerCase().includes(location)||p.title.toLowerCase().includes(location))&&(!type||p.type===type)&&(!price||(price==='under20'&&p.numeric<20)||(price==='20to100'&&p.numeric>=20&&p.numeric<=100)||(price==='over100'&&p.numeric>100)));render(filtered);document.getElementById('listings').scrollIntoView({behavior:'smooth'});});
const nav=document.getElementById('navPopover'),menu=document.querySelector('.menu-toggle');menu.addEventListener('click',()=>{const visible=nav.classList.toggle('show');menu.setAttribute('aria-expanded',visible)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('show');menu.setAttribute('aria-expanded','false')}));document.addEventListener('click',e=>{if(!nav.contains(e.target)&&!menu.contains(e.target)){nav.classList.remove('show');menu.setAttribute('aria-expanded','false')}});
const modalEl=document.getElementById('propertyModal'),modal=window.bootstrap?new bootstrap.Modal(modalEl):null;
function showProperty(slug){const p=properties.find(item=>item.slug===slug);if(!p||!modal)return;document.getElementById('modalImage').src=p.image;document.getElementById('modalImage').alt=p.title;document.getElementById('modalStatus').textContent=p.status;document.getElementById('modalTitle').textContent=p.title;document.getElementById('modalLocation').textContent=`⌖  ${p.location}`;document.getElementById('modalPrice').textContent=`${p.price} ${p.period||''}`;document.getElementById('modalDetails').textContent=`${p.beds} · ${p.baths} · ${p.size}. Contact Homephase Realty for a viewing and full property details.`;document.getElementById('modalWhatsapp').href=`https://wa.me/2349153079971?text=${encodeURIComponent(`Hi Homephase Realty, I'm interested in the ${p.title} in ${p.location}.`)}`;modal.show()}
grid.addEventListener('click',e=>{const c=e.target.closest('.property-card');if(c&&!e.target.closest('.favorite'))showProperty(c.dataset.slug)});grid.addEventListener('keydown',e=>{const c=e.target.closest('.property-card');if(c&&(e.key==='Enter'||e.key===' ')){e.preventDefault();showProperty(c.dataset.slug)}});




